### PR TITLE
fix: iterate over all nodes (#85)

### LINKED ISSUE #85: Plugin throws a nil value error
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/treesitter.lua:182: attempt to call method 'range' (a nil value)
stack traceback:
	/usr/share/nvim/runtime/lua/vim/treesitter.lua:182: in function 'get_range'
	/usr/share/nvim/runtime/lua/vim/treesitter.lua:217: in function 'get_node_text'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:165: in function 'set_virtual_text'
	...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:114: in function 'c'
	...acio/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1002: in function <...acio/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:996>

I'm using nvim nightly.
NVIM v0.11.0-dev-711+g7b7c95dac

### PR DESCRIPTION
**Pull request by b0o**
`Query:iter_matches` returns a `TSNode[]` iterator, but it was previously being treated a single `TSNode`. See [`:h Query:iter_matches()`](https://neovim.io/doc/user/treesitter.html#Query%3Aiter_matches()).

Note: I haven't tested this change in earlier nvim versions to see if it's backwards-compatible.
 
fixes #85

Related: https://github.com/neovim/neovim/pull/30193

### CODE REVIEW

**Comment by Espacio-root** [comment]
Yes! Works as expected now.

File: lua/nvim-dap-virtual-text/virtual_text.lua [hunk 1]
```diff
@@ -123,14 +123,16 @@ function M.set_virtual_text(stackframe, options)
     local query = get_query(ltree:lang(), 'locals')
     if query then
       for _, match, _ in query:iter_matches(tree:root(), buf, 0, -1) do
```
Comment (theHamsta) [inline lua/nvim-dap-virtual-text/virtual_text.lua:125]: With
```
, { all = true }
```
it would also be compatible with the old Neovim version that had `all = false` as a default.

Comment (b0o) [reply lua/nvim-dap-virtual-text/virtual_text.lua]: thanks, done

**Review by theHamsta — APPROVED** [review]
Thank you!
